export const GET_ELEMENT = 'PAYMENTS:GET_ELEMENT';
export const GET_LIST = 'PAYMENTS:GET_LIST';
export const CHARGE_VENUE = 'PAYMENTS:CHARGE_VENUE';
export const PAY_PROFESSIONAL = 'PAYMENTS:PAY_PROFESSIONAL';
export const RESET_PROFESSIONAL = 'PAYMENTS:RESET_PROFESSIONAL';
