export const GET_ELEMENT = 'VENUE:GET_ELEMENT';
export const GET_LIST = 'VENUE:GET_LIST';
export const GET_PAYMENT = 'VENUE:GET_PAYMENT';
export const GET_MANAGERS = 'VENUE:GET_MANAGERS';
export const SET_STATUS = 'VENUE:SET_STATUS';
